// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_sobel,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.512000,HLS_SYN_LAT=66069,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=1456,HLS_SYN_LUT=1581,HLS_VERSION=2024_2}" *)

module sobel (
        ap_clk,
        ap_rst_n,
        in_stream_TVALID,
        out_stream_TREADY,
        in_stream_TDATA,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   in_stream_TVALID;
input   out_stream_TREADY;
input  [7:0] in_stream_TDATA;
output   in_stream_TREADY;
input  [0:0] in_stream_TKEEP;
input  [0:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [7:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg   [0:0] tmp_4_reg_1295;
reg   [0:0] tmp_4_reg_1295_pp0_iter12_reg;
reg    ap_block_state14_pp0_stage0_iter13;
reg    ap_enable_reg_pp0_iter13;
reg   [0:0] and_ln35_reg_1305;
reg   [0:0] and_ln35_reg_1305_pp0_iter17_reg;
reg    ap_block_state19_pp0_stage0_iter18;
reg    ap_enable_reg_pp0_iter18;
reg   [0:0] and_ln35_reg_1305_pp0_iter18_reg;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg    ap_block_state20_pp0_stage0_iter19;
reg    ap_enable_reg_pp0_iter19;
wire    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln21_fu_676_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    out_stream_TDATA_blk_n;
reg   [7:0] reg_505;
reg    ap_enable_reg_pp0_iter14;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] and_ln35_reg_1305_pp0_iter13_reg;
reg   [1:0] trunc_ln22_1_reg_1338;
reg   [1:0] trunc_ln22_1_reg_1338_pp0_iter13_reg;
reg   [7:0] reg_505_pp0_iter15_reg;
reg   [7:0] reg_509;
reg   [7:0] reg_509_pp0_iter15_reg;
reg   [7:0] reg_513;
reg   [7:0] reg_513_pp0_iter15_reg;
reg   [7:0] reg_517;
reg   [7:0] reg_517_pp0_iter15_reg;
reg   [7:0] reg_517_pp0_iter16_reg;
reg   [0:0] tmp_3_reg_1286;
reg   [0:0] tmp_3_reg_1286_pp0_iter13_reg;
reg   [7:0] reg_521;
reg   [7:0] reg_521_pp0_iter15_reg;
reg   [7:0] reg_521_pp0_iter16_reg;
reg   [7:0] reg_525;
reg   [7:0] reg_525_pp0_iter15_reg;
reg   [7:0] reg_525_pp0_iter16_reg;
wire   [8:0] select_ln21_fu_561_p3;
reg   [8:0] select_ln21_reg_1268;
reg   [8:0] select_ln21_reg_1268_pp0_iter1_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter2_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter3_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter4_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter5_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter6_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter7_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter8_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter9_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter10_reg;
reg   [8:0] select_ln21_reg_1268_pp0_iter11_reg;
wire   [63:0] zext_ln22_fu_593_p1;
reg   [63:0] zext_ln22_reg_1275;
reg   [63:0] zext_ln22_reg_1275_pp0_iter1_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter2_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter3_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter4_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter5_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter6_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter7_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter8_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter9_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter10_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter11_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter12_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter13_reg;
reg   [63:0] zext_ln22_reg_1275_pp0_iter14_reg;
wire   [7:0] trunc_ln22_fu_598_p1;
reg   [7:0] trunc_ln22_reg_1280;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter1_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter2_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter3_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter4_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter5_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter6_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter7_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter8_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter9_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter10_reg;
reg   [7:0] trunc_ln22_reg_1280_pp0_iter11_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter1_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter2_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter3_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter4_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter5_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter6_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter7_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter8_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter9_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter10_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter11_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter12_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter14_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter15_reg;
reg   [0:0] tmp_3_reg_1286_pp0_iter16_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter1_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter2_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter3_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter4_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter5_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter6_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter7_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter8_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter9_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter10_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter11_reg;
reg   [0:0] tmp_4_reg_1295_pp0_iter13_reg;
reg   [7:0] line_buffer_1_addr_reg_1299;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter1_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter2_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter3_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter4_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter5_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter6_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter7_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter8_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter9_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter10_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter11_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter12_reg;
reg   [7:0] line_buffer_1_addr_reg_1299_pp0_iter13_reg;
wire   [0:0] and_ln35_fu_652_p2;
reg   [0:0] and_ln35_reg_1305_pp0_iter1_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter2_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter3_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter4_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter5_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter6_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter7_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter8_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter9_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter10_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter11_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter12_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter14_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter15_reg;
reg   [0:0] and_ln35_reg_1305_pp0_iter16_reg;
wire   [0:0] icmp_ln22_fu_664_p2;
reg   [0:0] icmp_ln22_reg_1309;
reg   [0:0] icmp_ln21_reg_1314;
reg   [7:0] line_buffer_1_load_reg_1318;
reg    ap_enable_reg_pp0_iter1;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter2_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter3_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter4_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter5_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter6_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter7_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter8_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter9_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter10_reg;
reg   [7:0] line_buffer_1_load_reg_1318_pp0_iter11_reg;
wire   [63:0] zext_ln22_1_fu_721_p1;
reg   [63:0] zext_ln22_1_reg_1325;
reg   [63:0] zext_ln22_1_reg_1325_pp0_iter13_reg;
wire   [1:0] trunc_ln22_1_fu_728_p1;
reg   [1:0] trunc_ln22_1_reg_1338_pp0_iter14_reg;
reg   [1:0] trunc_ln22_1_reg_1338_pp0_iter15_reg;
reg   [1:0] trunc_ln22_1_reg_1338_pp0_iter16_reg;
wire   [7:0] add_ln41_fu_732_p2;
reg   [7:0] add_ln41_reg_1349;
reg   [6:0] tmp_7_reg_1355;
wire   [0:0] pix_out_last_fu_762_p2;
reg   [0:0] pix_out_last_reg_1360;
reg   [0:0] pix_out_last_reg_1360_pp0_iter13_reg;
reg   [0:0] pix_out_last_reg_1360_pp0_iter14_reg;
reg   [0:0] pix_out_last_reg_1360_pp0_iter15_reg;
reg   [0:0] pix_out_last_reg_1360_pp0_iter16_reg;
reg   [0:0] pix_out_last_reg_1360_pp0_iter17_reg;
reg   [7:0] px_3_reg_1475;
reg   [7:0] px_3_reg_1475_pp0_iter15_reg;
reg   [7:0] line_buffer_load_3_reg_1480;
reg    ap_enable_reg_pp0_iter15;
reg   [7:0] line_buffer_1_load_3_reg_1485;
reg   [7:0] line_buffer_2_load_3_reg_1490;
wire   [10:0] gx_4_fu_1043_p2;
reg   [10:0] gx_4_reg_1500;
wire   [10:0] gy_3_fu_1090_p2;
reg   [10:0] gy_3_reg_1506;
wire   [7:0] add_ln52_fu_1205_p2;
reg   [7:0] add_ln52_reg_1512;
reg   [2:0] tmp_10_reg_1517;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
wire   [7:0] line_buffer_q0;
wire   [6:0] line_buffer_address1;
wire   [7:0] line_buffer_q1;
wire   [7:0] line_buffer_1_17_q0;
wire   [6:0] line_buffer_1_17_address1;
wire   [7:0] line_buffer_1_17_q1;
wire   [7:0] line_buffer_2_q0;
wire   [6:0] line_buffer_2_address1;
wire   [7:0] line_buffer_2_q1;
wire   [7:0] line_buffer_1_address1;
wire   [7:0] line_buffer_1_q1;
wire   [7:0] line_buffer_1_address2;
wire   [7:0] line_buffer_1_q2;
wire   [7:0] line_buffer_1_address3;
wire   [7:0] line_buffer_1_q3;
wire   [6:0] line_buffer_3_address0;
wire   [7:0] line_buffer_3_q1;
wire   [6:0] line_buffer_4_address0;
wire   [7:0] line_buffer_4_q1;
wire   [6:0] line_buffer_5_address0;
wire   [7:0] line_buffer_5_q1;
reg   [0:0] ap_phi_mux_icmp_ln2210_phi_fu_498_p4;
wire    ap_loop_init;
wire   [63:0] zext_ln41_1_fu_797_p1;
wire   [63:0] zext_ln41_4_fu_807_p1;
wire   [63:0] zext_ln41_fu_774_p1;
reg   [16:0] indvar_flatten7_fu_142;
wire   [16:0] add_ln21_fu_630_p2;
reg   [16:0] ap_sig_allocacmp_indvar_flatten7_load;
reg   [8:0] row8_fu_146;
wire   [8:0] row_2_fu_569_p3;
reg   [8:0] ap_sig_allocacmp_row8_load;
reg   [8:0] col9_fu_150;
wire   [8:0] col_fu_658_p2;
reg   [8:0] ap_sig_allocacmp_col9_load;
reg   [8:0] row_111_fu_154;
wire   [8:0] row_fu_670_p2;
reg   [8:0] ap_sig_allocacmp_row_111_load;
reg    ap_block_pp0_stage0_01001;
reg    line_buffer_1_ce3_local;
reg    line_buffer_1_ce2_local;
reg    line_buffer_1_we0_local;
wire   [7:0] tmp_fu_816_p9;
reg    line_buffer_1_ce0_local;
reg    line_buffer_1_ce1_local;
reg    line_buffer_4_we0_local;
reg    line_buffer_4_ce0_local;
reg    line_buffer_4_ce1_local;
reg   [6:0] line_buffer_4_address1_local;
reg    line_buffer_3_we0_local;
reg    line_buffer_3_ce0_local;
reg    line_buffer_3_ce1_local;
reg   [6:0] line_buffer_3_address1_local;
reg    line_buffer_5_we0_local;
reg    line_buffer_5_ce0_local;
reg    line_buffer_5_ce1_local;
reg   [6:0] line_buffer_5_address1_local;
reg    line_buffer_ce0_local;
reg   [6:0] line_buffer_address0_local;
reg    line_buffer_we0_local;
reg    line_buffer_ce1_local;
reg    line_buffer_1_17_ce0_local;
reg   [6:0] line_buffer_1_17_address0_local;
reg    line_buffer_1_17_we0_local;
reg    line_buffer_1_17_ce1_local;
reg    line_buffer_2_ce0_local;
reg   [6:0] line_buffer_2_address0_local;
reg    line_buffer_2_we0_local;
reg    line_buffer_2_ce1_local;
wire   [7:0] tmp_1_fu_577_p4;
wire   [2:0] grp_fu_602_p1;
wire   [8:0] or_ln27_fu_616_p2;
wire   [7:0] tmp_5_fu_636_p4;
wire   [0:0] icmp14_fu_587_p2;
wire   [0:0] icmp_ln35_fu_646_p2;
wire   [8:0] mul_ln22_fu_705_p0;
wire   [10:0] mul_ln22_fu_705_p1;
wire   [18:0] mul_ln22_fu_705_p2;
wire   [7:0] tmp_2_fu_711_p4;
wire   [1:0] grp_fu_602_p2;
wire   [7:0] add_ln41_1_fu_737_p2;
wire   [7:0] mul_ln41_1_fu_746_p0;
wire   [9:0] mul_ln41_1_fu_746_p1;
wire   [16:0] mul_ln41_1_fu_746_p2;
wire   [7:0] mul_ln41_fu_781_p0;
wire   [9:0] mul_ln41_fu_781_p1;
wire   [16:0] mul_ln41_fu_781_p2;
wire   [6:0] tmp_6_fu_787_p4;
wire   [7:0] tmp_fu_816_p7;
wire   [7:0] px_fu_836_p7;
wire   [7:0] px_fu_836_p9;
wire   [7:0] px_1_fu_863_p7;
wire   [7:0] px_1_fu_863_p9;
wire   [8:0] tmp_8_fu_882_p3;
wire   [9:0] zext_ln43_2_fu_890_p1;
wire   [9:0] sub_ln43_fu_894_p2;
wire  signed [10:0] sext_ln43_fu_900_p1;
wire   [10:0] zext_ln41_3_fu_859_p1;
wire   [7:0] px_2_fu_910_p7;
wire   [7:0] px_2_fu_910_p9;
wire   [10:0] gy_fu_904_p2;
wire   [10:0] zext_ln41_6_fu_926_p1;
wire   [10:0] gy_1_fu_930_p2;
wire   [7:0] conv_2218_pn_fu_943_p3;
wire   [8:0] zext_ln36_fu_950_p1;
wire   [8:0] zext_ln41_2_fu_855_p1;
wire   [8:0] gx_fu_954_p2;
wire   [8:0] tmp_9_fu_964_p3;
wire   [9:0] zext_ln42_1_fu_971_p1;
wire   [9:0] sub_ln42_fu_975_p2;
wire  signed [10:0] sext_ln42_fu_981_p1;
wire  signed [10:0] sext_ln36_fu_960_p1;
wire   [8:0] shl_ln_fu_991_p3;
wire   [10:0] zext_ln42_fu_999_p1;
wire   [10:0] gx_1_fu_985_p2;
wire   [10:0] gx_2_fu_1003_p2;
wire   [7:0] px_5_fu_1016_p7;
wire   [7:0] px_5_fu_1016_p9;
wire   [10:0] gx_3_fu_1009_p3;
wire   [10:0] zext_ln41_9_fu_1039_p1;
wire   [7:0] px_6_fu_1049_p7;
wire   [7:0] px_6_fu_1049_p9;
wire   [8:0] shl_ln1_fu_1068_p3;
wire   [9:0] zext_ln43_fu_1076_p1;
wire   [9:0] zext_ln41_8_fu_1035_p1;
wire   [9:0] add_ln43_fu_1080_p2;
wire   [10:0] zext_ln43_1_fu_1086_p1;
wire   [10:0] gy_2_fu_936_p3;
wire   [7:0] px_7_fu_1096_p7;
wire   [7:0] px_7_fu_1096_p9;
wire   [10:0] zext_ln41_10_fu_1115_p1;
wire   [10:0] gy_4_fu_1124_p2;
wire   [10:0] gy_5_fu_1129_p3;
wire   [10:0] gx_5_fu_1119_p2;
wire   [10:0] gx_6_fu_1139_p3;
wire   [9:0] trunc_ln36_1_fu_1145_p1;
wire   [0:0] abscond_fu_1155_p2;
wire   [9:0] neg_fu_1149_p2;
wire   [9:0] abs_fu_1161_p3;
wire   [9:0] trunc_ln36_fu_1135_p1;
wire   [0:0] abscond2_fu_1183_p2;
wire   [9:0] neg1_fu_1177_p2;
wire   [9:0] abs3_fu_1189_p3;
wire   [7:0] empty_22_fu_1169_p1;
wire   [7:0] trunc_ln49_fu_1197_p1;
wire   [10:0] abs_cast_fu_1173_p1;
wire   [10:0] zext_ln49_fu_1201_p1;
wire   [10:0] mag_fu_1211_p2;
wire   [0:0] icmp_ln50_fu_1227_p2;
reg    grp_fu_602_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_continue_int;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [7:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [0:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [0:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [7:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire   [18:0] mul_ln22_fu_705_p00;
wire   [16:0] mul_ln41_1_fu_746_p00;
wire   [16:0] mul_ln41_fu_781_p00;
reg    ap_condition_1408;
reg    ap_condition_283;
reg    ap_condition_606;
wire   [1:0] tmp_fu_816_p1;
wire   [1:0] tmp_fu_816_p3;
wire  signed [1:0] tmp_fu_816_p5;
wire  signed [1:0] px_fu_836_p1;
wire   [1:0] px_fu_836_p3;
wire   [1:0] px_fu_836_p5;
wire   [1:0] px_1_fu_863_p1;
wire  signed [1:0] px_1_fu_863_p3;
wire   [1:0] px_1_fu_863_p5;
wire   [1:0] px_2_fu_910_p1;
wire   [1:0] px_2_fu_910_p3;
wire  signed [1:0] px_2_fu_910_p5;
wire  signed [1:0] px_5_fu_1016_p1;
wire   [1:0] px_5_fu_1016_p3;
wire   [1:0] px_5_fu_1016_p5;
wire   [1:0] px_6_fu_1049_p1;
wire  signed [1:0] px_6_fu_1049_p3;
wire   [1:0] px_6_fu_1049_p5;
wire   [1:0] px_7_fu_1096_p1;
wire   [1:0] px_7_fu_1096_p3;
wire  signed [1:0] px_7_fu_1096_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 indvar_flatten7_fu_142 = 17'd0;
#0 row8_fu_146 = 9'd0;
#0 col9_fu_150 = 9'd0;
#0 row_111_fu_154 = 9'd0;
end

sobel_line_buffer_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 86 ),
    .AddressWidth( 7 ))
line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_address0_local),
    .ce0(line_buffer_ce0_local),
    .we0(line_buffer_we0_local),
    .d0(in_stream_TDATA_int_regslice),
    .q0(line_buffer_q0),
    .address1(line_buffer_address1),
    .ce1(line_buffer_ce1_local),
    .q1(line_buffer_q1)
);

sobel_line_buffer_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 86 ),
    .AddressWidth( 7 ))
line_buffer_1_17_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_1_17_address0_local),
    .ce0(line_buffer_1_17_ce0_local),
    .we0(line_buffer_1_17_we0_local),
    .d0(in_stream_TDATA_int_regslice),
    .q0(line_buffer_1_17_q0),
    .address1(line_buffer_1_17_address1),
    .ce1(line_buffer_1_17_ce1_local),
    .q1(line_buffer_1_17_q1)
);

sobel_line_buffer_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 86 ),
    .AddressWidth( 7 ))
line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_2_address0_local),
    .ce0(line_buffer_2_ce0_local),
    .we0(line_buffer_2_we0_local),
    .d0(in_stream_TDATA_int_regslice),
    .q0(line_buffer_2_q0),
    .address1(line_buffer_2_address1),
    .ce1(line_buffer_2_ce1_local),
    .q1(line_buffer_2_q1)
);

sobel_line_buffer_1_RAM_1WNR_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_1_addr_reg_1299_pp0_iter13_reg),
    .ce0(line_buffer_1_ce0_local),
    .we0(line_buffer_1_we0_local),
    .d0(tmp_fu_816_p9),
    .address1(line_buffer_1_address1),
    .ce1(line_buffer_1_ce1_local),
    .q1(line_buffer_1_q1),
    .address2(line_buffer_1_address2),
    .ce2(line_buffer_1_ce2_local),
    .q2(line_buffer_1_q2),
    .address3(line_buffer_1_address3),
    .ce3(line_buffer_1_ce3_local),
    .q3(line_buffer_1_q3)
);

sobel_line_buffer_3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 86 ),
    .AddressWidth( 7 ))
line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_3_address0),
    .ce0(line_buffer_3_ce0_local),
    .we0(line_buffer_3_we0_local),
    .d0(line_buffer_1_load_reg_1318_pp0_iter11_reg),
    .address1(line_buffer_3_address1_local),
    .ce1(line_buffer_3_ce1_local),
    .q1(line_buffer_3_q1)
);

sobel_line_buffer_3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 86 ),
    .AddressWidth( 7 ))
line_buffer_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_4_address0),
    .ce0(line_buffer_4_ce0_local),
    .we0(line_buffer_4_we0_local),
    .d0(line_buffer_1_load_reg_1318_pp0_iter11_reg),
    .address1(line_buffer_4_address1_local),
    .ce1(line_buffer_4_ce1_local),
    .q1(line_buffer_4_q1)
);

sobel_line_buffer_3_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 86 ),
    .AddressWidth( 7 ))
line_buffer_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(line_buffer_5_address0),
    .ce0(line_buffer_5_ce0_local),
    .we0(line_buffer_5_we0_local),
    .d0(line_buffer_1_load_reg_1318_pp0_iter11_reg),
    .address1(line_buffer_5_address1_local),
    .ce1(line_buffer_5_ce1_local),
    .q1(line_buffer_5_q1)
);

sobel_urem_9ns_3ns_2_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_9ns_3ns_2_13_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(select_ln21_fu_561_p3),
    .din1(grp_fu_602_p1),
    .ce(grp_fu_602_ce),
    .dout(grp_fu_602_p2)
);

sobel_mul_9ns_11ns_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 19 ))
mul_9ns_11ns_19_1_1_U2(
    .din0(mul_ln22_fu_705_p0),
    .din1(mul_ln22_fu_705_p1),
    .dout(mul_ln22_fu_705_p2)
);

sobel_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U3(
    .din0(mul_ln41_1_fu_746_p0),
    .din1(mul_ln41_1_fu_746_p1),
    .dout(mul_ln41_1_fu_746_p2)
);

sobel_mul_8ns_10ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 17 ))
mul_8ns_10ns_17_1_1_U4(
    .din0(mul_ln41_fu_781_p0),
    .din1(mul_ln41_fu_781_p1),
    .dout(mul_ln41_fu_781_p2)
);

(* dissolve_hierarchy = "yes" *) sobel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U5(
    .din0(line_buffer_q0),
    .din1(line_buffer_1_17_q0),
    .din2(line_buffer_2_q0),
    .def(tmp_fu_816_p7),
    .sel(trunc_ln22_1_reg_1338_pp0_iter13_reg),
    .dout(tmp_fu_816_p9)
);

(* dissolve_hierarchy = "yes" *) sobel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U6(
    .din0(reg_505_pp0_iter15_reg),
    .din1(reg_509_pp0_iter15_reg),
    .din2(reg_513_pp0_iter15_reg),
    .def(px_fu_836_p7),
    .sel(trunc_ln22_1_reg_1338_pp0_iter15_reg),
    .dout(px_fu_836_p9)
);

(* dissolve_hierarchy = "yes" *) sobel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U7(
    .din0(reg_505_pp0_iter15_reg),
    .din1(reg_509_pp0_iter15_reg),
    .din2(reg_513_pp0_iter15_reg),
    .def(px_1_fu_863_p7),
    .sel(trunc_ln22_1_reg_1338_pp0_iter15_reg),
    .dout(px_1_fu_863_p9)
);

(* dissolve_hierarchy = "yes" *) sobel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U8(
    .din0(line_buffer_load_3_reg_1480),
    .din1(line_buffer_1_load_3_reg_1485),
    .din2(line_buffer_2_load_3_reg_1490),
    .def(px_2_fu_910_p7),
    .sel(trunc_ln22_1_reg_1338_pp0_iter15_reg),
    .dout(px_2_fu_910_p9)
);

(* dissolve_hierarchy = "yes" *) sobel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h0 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h1 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U9(
    .din0(reg_517_pp0_iter15_reg),
    .din1(reg_521_pp0_iter15_reg),
    .din2(reg_525_pp0_iter15_reg),
    .def(px_5_fu_1016_p7),
    .sel(trunc_ln22_1_reg_1338_pp0_iter15_reg),
    .dout(px_5_fu_1016_p9)
);

(* dissolve_hierarchy = "yes" *) sobel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h1 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h2 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U10(
    .din0(reg_517_pp0_iter15_reg),
    .din1(reg_521_pp0_iter15_reg),
    .din2(reg_525_pp0_iter15_reg),
    .def(px_6_fu_1049_p7),
    .sel(trunc_ln22_1_reg_1338_pp0_iter15_reg),
    .dout(px_6_fu_1049_p9)
);

(* dissolve_hierarchy = "yes" *) sobel_sparsemux_7_2_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sparsemux_7_2_8_1_1_U11(
    .din0(reg_517_pp0_iter16_reg),
    .din1(reg_521_pp0_iter16_reg),
    .din2(reg_525_pp0_iter16_reg),
    .def(px_7_fu_1096_p7),
    .sel(trunc_ln22_1_reg_1338_pp0_iter16_reg),
    .dout(px_7_fu_1096_p9)
);

sobel_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

sobel_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd1),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(pix_out_last_reg_1360_pp0_iter17_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_283)) begin
        col9_fu_150 <= col_fu_658_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_283)) begin
    indvar_flatten7_fu_142 <= add_ln21_fu_630_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_283)) begin
    row8_fu_146 <= row_2_fu_569_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_283)) begin
    row_111_fu_154 <= row_fu_670_p2;
end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln41_reg_1349 <= add_ln41_fu_732_p2;
        add_ln52_reg_1512 <= add_ln52_fu_1205_p2;
        and_ln35_reg_1305_pp0_iter10_reg <= and_ln35_reg_1305_pp0_iter9_reg;
        and_ln35_reg_1305_pp0_iter11_reg <= and_ln35_reg_1305_pp0_iter10_reg;
        and_ln35_reg_1305_pp0_iter12_reg <= and_ln35_reg_1305_pp0_iter11_reg;
        and_ln35_reg_1305_pp0_iter13_reg <= and_ln35_reg_1305_pp0_iter12_reg;
        and_ln35_reg_1305_pp0_iter14_reg <= and_ln35_reg_1305_pp0_iter13_reg;
        and_ln35_reg_1305_pp0_iter15_reg <= and_ln35_reg_1305_pp0_iter14_reg;
        and_ln35_reg_1305_pp0_iter16_reg <= and_ln35_reg_1305_pp0_iter15_reg;
        and_ln35_reg_1305_pp0_iter17_reg <= and_ln35_reg_1305_pp0_iter16_reg;
        and_ln35_reg_1305_pp0_iter18_reg <= and_ln35_reg_1305_pp0_iter17_reg;
        and_ln35_reg_1305_pp0_iter2_reg <= and_ln35_reg_1305_pp0_iter1_reg;
        and_ln35_reg_1305_pp0_iter3_reg <= and_ln35_reg_1305_pp0_iter2_reg;
        and_ln35_reg_1305_pp0_iter4_reg <= and_ln35_reg_1305_pp0_iter3_reg;
        and_ln35_reg_1305_pp0_iter5_reg <= and_ln35_reg_1305_pp0_iter4_reg;
        and_ln35_reg_1305_pp0_iter6_reg <= and_ln35_reg_1305_pp0_iter5_reg;
        and_ln35_reg_1305_pp0_iter7_reg <= and_ln35_reg_1305_pp0_iter6_reg;
        and_ln35_reg_1305_pp0_iter8_reg <= and_ln35_reg_1305_pp0_iter7_reg;
        and_ln35_reg_1305_pp0_iter9_reg <= and_ln35_reg_1305_pp0_iter8_reg;
        gx_4_reg_1500 <= gx_4_fu_1043_p2;
        gy_3_reg_1506 <= gy_3_fu_1090_p2;
        line_buffer_1_addr_reg_1299_pp0_iter10_reg <= line_buffer_1_addr_reg_1299_pp0_iter9_reg;
        line_buffer_1_addr_reg_1299_pp0_iter11_reg <= line_buffer_1_addr_reg_1299_pp0_iter10_reg;
        line_buffer_1_addr_reg_1299_pp0_iter12_reg <= line_buffer_1_addr_reg_1299_pp0_iter11_reg;
        line_buffer_1_addr_reg_1299_pp0_iter13_reg <= line_buffer_1_addr_reg_1299_pp0_iter12_reg;
        line_buffer_1_addr_reg_1299_pp0_iter2_reg <= line_buffer_1_addr_reg_1299_pp0_iter1_reg;
        line_buffer_1_addr_reg_1299_pp0_iter3_reg <= line_buffer_1_addr_reg_1299_pp0_iter2_reg;
        line_buffer_1_addr_reg_1299_pp0_iter4_reg <= line_buffer_1_addr_reg_1299_pp0_iter3_reg;
        line_buffer_1_addr_reg_1299_pp0_iter5_reg <= line_buffer_1_addr_reg_1299_pp0_iter4_reg;
        line_buffer_1_addr_reg_1299_pp0_iter6_reg <= line_buffer_1_addr_reg_1299_pp0_iter5_reg;
        line_buffer_1_addr_reg_1299_pp0_iter7_reg <= line_buffer_1_addr_reg_1299_pp0_iter6_reg;
        line_buffer_1_addr_reg_1299_pp0_iter8_reg <= line_buffer_1_addr_reg_1299_pp0_iter7_reg;
        line_buffer_1_addr_reg_1299_pp0_iter9_reg <= line_buffer_1_addr_reg_1299_pp0_iter8_reg;
        line_buffer_1_load_reg_1318_pp0_iter10_reg <= line_buffer_1_load_reg_1318_pp0_iter9_reg;
        line_buffer_1_load_reg_1318_pp0_iter11_reg <= line_buffer_1_load_reg_1318_pp0_iter10_reg;
        line_buffer_1_load_reg_1318_pp0_iter2_reg <= line_buffer_1_load_reg_1318;
        line_buffer_1_load_reg_1318_pp0_iter3_reg <= line_buffer_1_load_reg_1318_pp0_iter2_reg;
        line_buffer_1_load_reg_1318_pp0_iter4_reg <= line_buffer_1_load_reg_1318_pp0_iter3_reg;
        line_buffer_1_load_reg_1318_pp0_iter5_reg <= line_buffer_1_load_reg_1318_pp0_iter4_reg;
        line_buffer_1_load_reg_1318_pp0_iter6_reg <= line_buffer_1_load_reg_1318_pp0_iter5_reg;
        line_buffer_1_load_reg_1318_pp0_iter7_reg <= line_buffer_1_load_reg_1318_pp0_iter6_reg;
        line_buffer_1_load_reg_1318_pp0_iter8_reg <= line_buffer_1_load_reg_1318_pp0_iter7_reg;
        line_buffer_1_load_reg_1318_pp0_iter9_reg <= line_buffer_1_load_reg_1318_pp0_iter8_reg;
        pix_out_last_reg_1360 <= pix_out_last_fu_762_p2;
        pix_out_last_reg_1360_pp0_iter13_reg <= pix_out_last_reg_1360;
        pix_out_last_reg_1360_pp0_iter14_reg <= pix_out_last_reg_1360_pp0_iter13_reg;
        pix_out_last_reg_1360_pp0_iter15_reg <= pix_out_last_reg_1360_pp0_iter14_reg;
        pix_out_last_reg_1360_pp0_iter16_reg <= pix_out_last_reg_1360_pp0_iter15_reg;
        pix_out_last_reg_1360_pp0_iter17_reg <= pix_out_last_reg_1360_pp0_iter16_reg;
        px_3_reg_1475_pp0_iter15_reg <= px_3_reg_1475;
        reg_505_pp0_iter15_reg <= reg_505;
        reg_509_pp0_iter15_reg <= reg_509;
        reg_513_pp0_iter15_reg <= reg_513;
        reg_517_pp0_iter15_reg <= reg_517;
        reg_517_pp0_iter16_reg <= reg_517_pp0_iter15_reg;
        reg_521_pp0_iter15_reg <= reg_521;
        reg_521_pp0_iter16_reg <= reg_521_pp0_iter15_reg;
        reg_525_pp0_iter15_reg <= reg_525;
        reg_525_pp0_iter16_reg <= reg_525_pp0_iter15_reg;
        select_ln21_reg_1268_pp0_iter10_reg <= select_ln21_reg_1268_pp0_iter9_reg;
        select_ln21_reg_1268_pp0_iter11_reg <= select_ln21_reg_1268_pp0_iter10_reg;
        select_ln21_reg_1268_pp0_iter2_reg <= select_ln21_reg_1268_pp0_iter1_reg;
        select_ln21_reg_1268_pp0_iter3_reg <= select_ln21_reg_1268_pp0_iter2_reg;
        select_ln21_reg_1268_pp0_iter4_reg <= select_ln21_reg_1268_pp0_iter3_reg;
        select_ln21_reg_1268_pp0_iter5_reg <= select_ln21_reg_1268_pp0_iter4_reg;
        select_ln21_reg_1268_pp0_iter6_reg <= select_ln21_reg_1268_pp0_iter5_reg;
        select_ln21_reg_1268_pp0_iter7_reg <= select_ln21_reg_1268_pp0_iter6_reg;
        select_ln21_reg_1268_pp0_iter8_reg <= select_ln21_reg_1268_pp0_iter7_reg;
        select_ln21_reg_1268_pp0_iter9_reg <= select_ln21_reg_1268_pp0_iter8_reg;
        tmp_10_reg_1517 <= {{mag_fu_1211_p2[10:8]}};
        tmp_3_reg_1286_pp0_iter10_reg <= tmp_3_reg_1286_pp0_iter9_reg;
        tmp_3_reg_1286_pp0_iter11_reg <= tmp_3_reg_1286_pp0_iter10_reg;
        tmp_3_reg_1286_pp0_iter12_reg <= tmp_3_reg_1286_pp0_iter11_reg;
        tmp_3_reg_1286_pp0_iter13_reg <= tmp_3_reg_1286_pp0_iter12_reg;
        tmp_3_reg_1286_pp0_iter14_reg <= tmp_3_reg_1286_pp0_iter13_reg;
        tmp_3_reg_1286_pp0_iter15_reg <= tmp_3_reg_1286_pp0_iter14_reg;
        tmp_3_reg_1286_pp0_iter16_reg <= tmp_3_reg_1286_pp0_iter15_reg;
        tmp_3_reg_1286_pp0_iter2_reg <= tmp_3_reg_1286_pp0_iter1_reg;
        tmp_3_reg_1286_pp0_iter3_reg <= tmp_3_reg_1286_pp0_iter2_reg;
        tmp_3_reg_1286_pp0_iter4_reg <= tmp_3_reg_1286_pp0_iter3_reg;
        tmp_3_reg_1286_pp0_iter5_reg <= tmp_3_reg_1286_pp0_iter4_reg;
        tmp_3_reg_1286_pp0_iter6_reg <= tmp_3_reg_1286_pp0_iter5_reg;
        tmp_3_reg_1286_pp0_iter7_reg <= tmp_3_reg_1286_pp0_iter6_reg;
        tmp_3_reg_1286_pp0_iter8_reg <= tmp_3_reg_1286_pp0_iter7_reg;
        tmp_3_reg_1286_pp0_iter9_reg <= tmp_3_reg_1286_pp0_iter8_reg;
        tmp_4_reg_1295_pp0_iter10_reg <= tmp_4_reg_1295_pp0_iter9_reg;
        tmp_4_reg_1295_pp0_iter11_reg <= tmp_4_reg_1295_pp0_iter10_reg;
        tmp_4_reg_1295_pp0_iter12_reg <= tmp_4_reg_1295_pp0_iter11_reg;
        tmp_4_reg_1295_pp0_iter13_reg <= tmp_4_reg_1295_pp0_iter12_reg;
        tmp_4_reg_1295_pp0_iter2_reg <= tmp_4_reg_1295_pp0_iter1_reg;
        tmp_4_reg_1295_pp0_iter3_reg <= tmp_4_reg_1295_pp0_iter2_reg;
        tmp_4_reg_1295_pp0_iter4_reg <= tmp_4_reg_1295_pp0_iter3_reg;
        tmp_4_reg_1295_pp0_iter5_reg <= tmp_4_reg_1295_pp0_iter4_reg;
        tmp_4_reg_1295_pp0_iter6_reg <= tmp_4_reg_1295_pp0_iter5_reg;
        tmp_4_reg_1295_pp0_iter7_reg <= tmp_4_reg_1295_pp0_iter6_reg;
        tmp_4_reg_1295_pp0_iter8_reg <= tmp_4_reg_1295_pp0_iter7_reg;
        tmp_4_reg_1295_pp0_iter9_reg <= tmp_4_reg_1295_pp0_iter8_reg;
        tmp_7_reg_1355 <= {{mul_ln41_1_fu_746_p2[16:10]}};
        trunc_ln22_1_reg_1338 <= trunc_ln22_1_fu_728_p1;
        trunc_ln22_1_reg_1338_pp0_iter13_reg <= trunc_ln22_1_reg_1338;
        trunc_ln22_1_reg_1338_pp0_iter14_reg <= trunc_ln22_1_reg_1338_pp0_iter13_reg;
        trunc_ln22_1_reg_1338_pp0_iter15_reg <= trunc_ln22_1_reg_1338_pp0_iter14_reg;
        trunc_ln22_1_reg_1338_pp0_iter16_reg <= trunc_ln22_1_reg_1338_pp0_iter15_reg;
        trunc_ln22_reg_1280_pp0_iter10_reg <= trunc_ln22_reg_1280_pp0_iter9_reg;
        trunc_ln22_reg_1280_pp0_iter11_reg <= trunc_ln22_reg_1280_pp0_iter10_reg;
        trunc_ln22_reg_1280_pp0_iter2_reg <= trunc_ln22_reg_1280_pp0_iter1_reg;
        trunc_ln22_reg_1280_pp0_iter3_reg <= trunc_ln22_reg_1280_pp0_iter2_reg;
        trunc_ln22_reg_1280_pp0_iter4_reg <= trunc_ln22_reg_1280_pp0_iter3_reg;
        trunc_ln22_reg_1280_pp0_iter5_reg <= trunc_ln22_reg_1280_pp0_iter4_reg;
        trunc_ln22_reg_1280_pp0_iter6_reg <= trunc_ln22_reg_1280_pp0_iter5_reg;
        trunc_ln22_reg_1280_pp0_iter7_reg <= trunc_ln22_reg_1280_pp0_iter6_reg;
        trunc_ln22_reg_1280_pp0_iter8_reg <= trunc_ln22_reg_1280_pp0_iter7_reg;
        trunc_ln22_reg_1280_pp0_iter9_reg <= trunc_ln22_reg_1280_pp0_iter8_reg;
        zext_ln22_1_reg_1325[7 : 0] <= zext_ln22_1_fu_721_p1[7 : 0];
        zext_ln22_1_reg_1325_pp0_iter13_reg[7 : 0] <= zext_ln22_1_reg_1325[7 : 0];
        zext_ln22_reg_1275_pp0_iter10_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter9_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter11_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter10_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter12_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter11_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter13_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter12_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter14_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter13_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter2_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter1_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter3_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter2_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter4_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter3_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter5_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter4_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter6_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter5_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter7_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter6_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter8_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter7_reg[8 : 0];
        zext_ln22_reg_1275_pp0_iter9_reg[8 : 0] <= zext_ln22_reg_1275_pp0_iter8_reg[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln35_reg_1305 <= and_ln35_fu_652_p2;
        and_ln35_reg_1305_pp0_iter1_reg <= and_ln35_reg_1305;
        icmp_ln21_reg_1314 <= icmp_ln21_fu_676_p2;
        line_buffer_1_addr_reg_1299 <= zext_ln22_fu_593_p1;
        line_buffer_1_addr_reg_1299_pp0_iter1_reg <= line_buffer_1_addr_reg_1299;
        select_ln21_reg_1268 <= select_ln21_fu_561_p3;
        select_ln21_reg_1268_pp0_iter1_reg <= select_ln21_reg_1268;
        tmp_3_reg_1286 <= select_ln21_fu_561_p3[32'd8];
        tmp_3_reg_1286_pp0_iter1_reg <= tmp_3_reg_1286;
        tmp_4_reg_1295 <= or_ln27_fu_616_p2[32'd8];
        tmp_4_reg_1295_pp0_iter1_reg <= tmp_4_reg_1295;
        trunc_ln22_reg_1280 <= trunc_ln22_fu_598_p1;
        trunc_ln22_reg_1280_pp0_iter1_reg <= trunc_ln22_reg_1280;
        zext_ln22_reg_1275[8 : 0] <= zext_ln22_fu_593_p1[8 : 0];
        zext_ln22_reg_1275_pp0_iter1_reg[8 : 0] <= zext_ln22_reg_1275[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln22_reg_1309 <= icmp_ln22_fu_664_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        line_buffer_1_load_3_reg_1485 <= line_buffer_1_17_q1;
        line_buffer_2_load_3_reg_1490 <= line_buffer_2_q1;
        line_buffer_load_3_reg_1480 <= line_buffer_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_load_reg_1318 <= line_buffer_1_q3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        px_3_reg_1475 <= line_buffer_1_q2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd2) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
        reg_505 <= line_buffer_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd2) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
        reg_509 <= line_buffer_1_17_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
        reg_513 <= line_buffer_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (tmp_3_reg_1286_pp0_iter13_reg == 1'd0) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd2) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
        reg_517 <= line_buffer_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (tmp_3_reg_1286_pp0_iter13_reg == 1'd0) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd2) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
        reg_521 <= line_buffer_4_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (tmp_3_reg_1286_pp0_iter13_reg == 1'd0) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd2) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd0) & (ap_enable_reg_pp0_iter14 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln35_reg_1305_pp0_iter13_reg) & (trunc_ln22_1_reg_1338_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1)))) begin
        reg_525 <= line_buffer_5_q1;
    end
end

always @ (*) begin
    if (((icmp_ln21_fu_676_p2 == 1'd1) & (1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_1408)) begin
            ap_phi_mux_icmp_ln2210_phi_fu_498_p4 = icmp_ln22_reg_1309;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln2210_phi_fu_498_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln2210_phi_fu_498_p4 = icmp_ln22_reg_1309;
        end
    end else begin
        ap_phi_mux_icmp_ln2210_phi_fu_498_p4 = icmp_ln22_reg_1309;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_col9_load = 9'd0;
    end else begin
        ap_sig_allocacmp_col9_load = col9_fu_150;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten7_load = 17'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten7_load = indvar_flatten7_fu_142;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_row8_load = 9'd0;
    end else begin
        ap_sig_allocacmp_row8_load = row8_fu_146;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_row_111_load = 9'd1;
    end else begin
        ap_sig_allocacmp_row_111_load = row_111_fu_154;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_602_ce = 1'b1;
    end else begin
        grp_fu_602_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int_regslice;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        if (((1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd2))) begin
            line_buffer_1_17_address0_local = zext_ln41_4_fu_807_p1;
        end else if (((1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd0))) begin
            line_buffer_1_17_address0_local = zext_ln41_1_fu_797_p1;
        end else if (((tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd1))) begin
            line_buffer_1_17_address0_local = zext_ln22_1_reg_1325;
        end else begin
            line_buffer_1_17_address0_local = 'bx;
        end
    end else begin
        line_buffer_1_17_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd1)))) begin
        line_buffer_1_17_ce0_local = 1'b1;
    end else begin
        line_buffer_1_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        line_buffer_1_17_ce1_local = 1'b1;
    end else begin
        line_buffer_1_17_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd1))) begin
        line_buffer_1_17_we0_local = 1'b1;
    end else begin
        line_buffer_1_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        line_buffer_1_ce0_local = 1'b1;
    end else begin
        line_buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        line_buffer_1_ce1_local = 1'b1;
    end else begin
        line_buffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        line_buffer_1_ce2_local = 1'b1;
    end else begin
        line_buffer_1_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_1_ce3_local = 1'b1;
    end else begin
        line_buffer_1_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_4_reg_1295_pp0_iter13_reg == 1'd0) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        line_buffer_1_we0_local = 1'b1;
    end else begin
        line_buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd0))) begin
        line_buffer_2_address0_local = zext_ln41_4_fu_807_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd1))) begin
        line_buffer_2_address0_local = zext_ln41_1_fu_797_p1;
    end else if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd2)) | (~(trunc_ln22_1_reg_1338 == 2'd1) & ~(trunc_ln22_1_reg_1338 == 2'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0)))) begin
        line_buffer_2_address0_local = zext_ln22_1_reg_1325;
    end else begin
        line_buffer_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((~(trunc_ln22_1_reg_1338 == 2'd1) & ~(trunc_ln22_1_reg_1338 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd2)))) begin
        line_buffer_2_ce0_local = 1'b1;
    end else begin
        line_buffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        line_buffer_2_ce1_local = 1'b1;
    end else begin
        line_buffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln22_1_reg_1338 == 2'd1) & ~(trunc_ln22_1_reg_1338 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0))) begin
        line_buffer_2_we0_local = 1'b1;
    end else begin
        line_buffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_606)) begin
        if (((tmp_3_reg_1286_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd0))) begin
            line_buffer_3_address1_local = zext_ln22_1_reg_1325;
        end else if ((trunc_ln22_1_reg_1338 == 2'd1)) begin
            line_buffer_3_address1_local = zext_ln41_4_fu_807_p1;
        end else if ((trunc_ln22_1_reg_1338 == 2'd2)) begin
            line_buffer_3_address1_local = zext_ln41_1_fu_797_p1;
        end else begin
            line_buffer_3_address1_local = 'bx;
        end
    end else begin
        line_buffer_3_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        line_buffer_3_ce0_local = 1'b1;
    end else begin
        line_buffer_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (tmp_3_reg_1286_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd2)))) begin
        line_buffer_3_ce1_local = 1'b1;
    end else begin
        line_buffer_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln22_1_fu_728_p1 == 2'd0) & (tmp_4_reg_1295_pp0_iter11_reg == 1'd0))) begin
        line_buffer_3_we0_local = 1'b1;
    end else begin
        line_buffer_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_606)) begin
        if (((tmp_3_reg_1286_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd1))) begin
            line_buffer_4_address1_local = zext_ln22_1_reg_1325;
        end else if ((trunc_ln22_1_reg_1338 == 2'd2)) begin
            line_buffer_4_address1_local = zext_ln41_4_fu_807_p1;
        end else if ((trunc_ln22_1_reg_1338 == 2'd0)) begin
            line_buffer_4_address1_local = zext_ln41_1_fu_797_p1;
        end else begin
            line_buffer_4_address1_local = 'bx;
        end
    end else begin
        line_buffer_4_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        line_buffer_4_ce0_local = 1'b1;
    end else begin
        line_buffer_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (tmp_3_reg_1286_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd2)))) begin
        line_buffer_4_ce1_local = 1'b1;
    end else begin
        line_buffer_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (trunc_ln22_1_fu_728_p1 == 2'd1) & (tmp_4_reg_1295_pp0_iter11_reg == 1'd0))) begin
        line_buffer_4_we0_local = 1'b1;
    end else begin
        line_buffer_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_606)) begin
        if (((tmp_3_reg_1286_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd2))) begin
            line_buffer_5_address1_local = zext_ln22_1_reg_1325;
        end else if ((trunc_ln22_1_reg_1338 == 2'd0)) begin
            line_buffer_5_address1_local = zext_ln41_4_fu_807_p1;
        end else if ((trunc_ln22_1_reg_1338 == 2'd1)) begin
            line_buffer_5_address1_local = zext_ln41_1_fu_797_p1;
        end else begin
            line_buffer_5_address1_local = 'bx;
        end
    end else begin
        line_buffer_5_address1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        line_buffer_5_ce0_local = 1'b1;
    end else begin
        line_buffer_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (tmp_3_reg_1286_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd0)))) begin
        line_buffer_5_ce1_local = 1'b1;
    end else begin
        line_buffer_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln22_1_fu_728_p1 == 2'd0) & ~(trunc_ln22_1_fu_728_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1) & (tmp_4_reg_1295_pp0_iter11_reg == 1'd0))) begin
        line_buffer_5_we0_local = 1'b1;
    end else begin
        line_buffer_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        if (((1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd1))) begin
            line_buffer_address0_local = zext_ln41_4_fu_807_p1;
        end else if (((1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd2))) begin
            line_buffer_address0_local = zext_ln41_1_fu_797_p1;
        end else if (((tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd0))) begin
            line_buffer_address0_local = zext_ln22_1_reg_1325;
        end else begin
            line_buffer_address0_local = 'bx;
        end
    end else begin
        line_buffer_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg) & (trunc_ln22_1_reg_1338 == 2'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd0)))) begin
        line_buffer_ce0_local = 1'b1;
    end else begin
        line_buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        line_buffer_ce1_local = 1'b1;
    end else begin
        line_buffer_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (trunc_ln22_1_reg_1338 == 2'd0))) begin
        line_buffer_we0_local = 1'b1;
    end else begin
        line_buffer_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter19 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter18_reg)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter18 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter17_reg)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter17_reg))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs3_fu_1189_p3 = ((abscond2_fu_1183_p2[0:0] == 1'b1) ? trunc_ln36_fu_1135_p1 : neg1_fu_1177_p2);

assign abs_cast_fu_1173_p1 = abs_fu_1161_p3;

assign abs_fu_1161_p3 = ((abscond_fu_1155_p2[0:0] == 1'b1) ? trunc_ln36_1_fu_1145_p1 : neg_fu_1149_p2);

assign abscond2_fu_1183_p2 = (($signed(gy_5_fu_1129_p3) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign abscond_fu_1155_p2 = (($signed(gx_6_fu_1139_p3) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign add_ln21_fu_630_p2 = (ap_sig_allocacmp_indvar_flatten7_load + 17'd1);

assign add_ln41_1_fu_737_p2 = ($signed(trunc_ln22_reg_1280_pp0_iter11_reg) + $signed(8'd255));

assign add_ln41_fu_732_p2 = ($signed(trunc_ln22_reg_1280_pp0_iter11_reg) + $signed(8'd254));

assign add_ln43_fu_1080_p2 = (zext_ln43_fu_1076_p1 + zext_ln41_8_fu_1035_p1);

assign add_ln52_fu_1205_p2 = (empty_22_fu_1169_p1 + trunc_ln49_fu_1197_p1);

assign and_ln35_fu_652_p2 = (icmp_ln35_fu_646_p2 & icmp14_fu_587_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) | ((1'b1 == ap_block_state20_pp0_stage0_iter19) & (ap_enable_reg_pp0_iter19 == 1'b1)) | ((1'b1 == ap_block_state19_pp0_stage0_iter18) & (ap_enable_reg_pp0_iter18 == 1'b1)) | ((1'b1 == ap_block_state14_pp0_stage0_iter13) & (ap_enable_reg_pp0_iter13 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) | ((1'b1 == ap_block_state20_pp0_stage0_iter19) & (ap_enable_reg_pp0_iter19 == 1'b1)) | ((1'b1 == ap_block_state19_pp0_stage0_iter18) & (ap_enable_reg_pp0_iter18 == 1'b1)) | ((1'b1 == ap_block_state14_pp0_stage0_iter13) & (ap_enable_reg_pp0_iter13 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) | ((1'b1 == ap_block_state20_pp0_stage0_iter19) & (ap_enable_reg_pp0_iter19 == 1'b1)) | ((1'b1 == ap_block_state19_pp0_stage0_iter18) & (ap_enable_reg_pp0_iter18 == 1'b1)) | ((1'b1 == ap_block_state14_pp0_stage0_iter13) & (ap_enable_reg_pp0_iter13 == 1'b1)));
end

always @ (*) begin
    ap_block_state14_pp0_stage0_iter13 = ((tmp_4_reg_1295_pp0_iter12_reg == 1'd0) & (in_stream_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state19_pp0_stage0_iter18 = ((1'd1 == and_ln35_reg_1305_pp0_iter17_reg) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state20_pp0_stage0_iter19 = ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | ((1'd1 == and_ln35_reg_1305_pp0_iter18_reg) & (out_stream_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_1408 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln21_reg_1314 == 1'd0));
end

always @ (*) begin
    ap_condition_283 = ((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_606 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter13 == 1'b1) & (1'd1 == and_ln35_reg_1305_pp0_iter12_reg));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready_pp0_iter19_reg = 1'b0;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign col_fu_658_p2 = (select_ln21_fu_561_p3 + 9'd1);

assign conv_2218_pn_fu_943_p3 = ((tmp_3_reg_1286_pp0_iter15_reg[0:0] == 1'b1) ? 8'd0 : px_2_fu_910_p9);

assign empty_22_fu_1169_p1 = abs_fu_1161_p3[7:0];

assign grp_fu_602_p1 = 9'd3;

assign gx_1_fu_985_p2 = ($signed(sext_ln42_fu_981_p1) + $signed(sext_ln36_fu_960_p1));

assign gx_2_fu_1003_p2 = (zext_ln42_fu_999_p1 + gx_1_fu_985_p2);

assign gx_3_fu_1009_p3 = ((tmp_3_reg_1286_pp0_iter15_reg[0:0] == 1'b1) ? gx_1_fu_985_p2 : gx_2_fu_1003_p2);

assign gx_4_fu_1043_p2 = (gx_3_fu_1009_p3 - zext_ln41_9_fu_1039_p1);

assign gx_5_fu_1119_p2 = (gx_4_reg_1500 + zext_ln41_10_fu_1115_p1);

assign gx_6_fu_1139_p3 = ((tmp_3_reg_1286_pp0_iter16_reg[0:0] == 1'b1) ? gx_4_reg_1500 : gx_5_fu_1119_p2);

assign gx_fu_954_p2 = (zext_ln36_fu_950_p1 - zext_ln41_2_fu_855_p1);

assign gy_1_fu_930_p2 = (gy_fu_904_p2 - zext_ln41_6_fu_926_p1);

assign gy_2_fu_936_p3 = ((tmp_3_reg_1286_pp0_iter15_reg[0:0] == 1'b1) ? gy_fu_904_p2 : gy_1_fu_930_p2);

assign gy_3_fu_1090_p2 = (zext_ln43_1_fu_1086_p1 + gy_2_fu_936_p3);

assign gy_4_fu_1124_p2 = (gy_3_reg_1506 + zext_ln41_10_fu_1115_p1);

assign gy_5_fu_1129_p3 = ((tmp_3_reg_1286_pp0_iter16_reg[0:0] == 1'b1) ? gy_3_reg_1506 : gy_4_fu_1124_p2);

assign gy_fu_904_p2 = ($signed(sext_ln43_fu_900_p1) - $signed(zext_ln41_3_fu_859_p1));

assign icmp14_fu_587_p2 = ((tmp_1_fu_577_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_676_p2 = ((ap_sig_allocacmp_indvar_flatten7_load == 17'd66048) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_664_p2 = ((col_fu_658_p2 == 9'd257) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_646_p2 = ((tmp_5_fu_636_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_1227_p2 = ((tmp_10_reg_1517 != 3'd0) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign line_buffer_1_17_address1 = zext_ln22_1_reg_1325_pp0_iter13_reg;

assign line_buffer_1_address1 = zext_ln22_reg_1275_pp0_iter14_reg;

assign line_buffer_1_address2 = zext_ln41_fu_774_p1;

assign line_buffer_1_address3 = zext_ln22_fu_593_p1;

assign line_buffer_2_address1 = zext_ln22_1_reg_1325_pp0_iter13_reg;

assign line_buffer_3_address0 = zext_ln22_1_fu_721_p1;

assign line_buffer_4_address0 = zext_ln22_1_fu_721_p1;

assign line_buffer_5_address0 = zext_ln22_1_fu_721_p1;

assign line_buffer_address1 = zext_ln22_1_reg_1325_pp0_iter13_reg;

assign mag_fu_1211_p2 = (abs_cast_fu_1173_p1 + zext_ln49_fu_1201_p1);

assign mul_ln22_fu_705_p0 = mul_ln22_fu_705_p00;

assign mul_ln22_fu_705_p00 = select_ln21_reg_1268_pp0_iter11_reg;

assign mul_ln22_fu_705_p1 = 19'd683;

assign mul_ln41_1_fu_746_p0 = mul_ln41_1_fu_746_p00;

assign mul_ln41_1_fu_746_p00 = add_ln41_1_fu_737_p2;

assign mul_ln41_1_fu_746_p1 = 17'd342;

assign mul_ln41_fu_781_p0 = mul_ln41_fu_781_p00;

assign mul_ln41_fu_781_p00 = add_ln41_reg_1349;

assign mul_ln41_fu_781_p1 = 17'd342;

assign neg1_fu_1177_p2 = (10'd0 - trunc_ln36_fu_1135_p1);

assign neg_fu_1149_p2 = (10'd0 - trunc_ln36_1_fu_1145_p1);

assign or_ln27_fu_616_p2 = (select_ln21_fu_561_p3 | row_2_fu_569_p3);

assign out_stream_TDATA_int_regslice = ((icmp_ln50_fu_1227_p2[0:0] == 1'b1) ? 8'd255 : add_ln52_reg_1512);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign pix_out_last_fu_762_p2 = ((select_ln21_reg_1268_pp0_iter11_reg == 9'd256) ? 1'b1 : 1'b0);

assign px_1_fu_863_p7 = 'bx;

assign px_2_fu_910_p7 = 'bx;

assign px_5_fu_1016_p7 = 'bx;

assign px_6_fu_1049_p7 = 'bx;

assign px_7_fu_1096_p7 = 'bx;

assign px_fu_836_p7 = 'bx;

assign row_2_fu_569_p3 = ((ap_phi_mux_icmp_ln2210_phi_fu_498_p4[0:0] == 1'b1) ? ap_sig_allocacmp_row_111_load : ap_sig_allocacmp_row8_load);

assign row_fu_670_p2 = (row_2_fu_569_p3 + 9'd1);

assign select_ln21_fu_561_p3 = ((ap_phi_mux_icmp_ln2210_phi_fu_498_p4[0:0] == 1'b1) ? 9'd0 : ap_sig_allocacmp_col9_load);

assign sext_ln36_fu_960_p1 = $signed(gx_fu_954_p2);

assign sext_ln42_fu_981_p1 = $signed(sub_ln42_fu_975_p2);

assign sext_ln43_fu_900_p1 = $signed(sub_ln43_fu_894_p2);

assign shl_ln1_fu_1068_p3 = {{px_6_fu_1049_p9}, {1'd0}};

assign shl_ln_fu_991_p3 = {{line_buffer_1_q1}, {1'd0}};

assign sub_ln42_fu_975_p2 = (10'd0 - zext_ln42_1_fu_971_p1);

assign sub_ln43_fu_894_p2 = (10'd0 - zext_ln43_2_fu_890_p1);

assign tmp_1_fu_577_p4 = {{row_2_fu_569_p3[8:1]}};

assign tmp_2_fu_711_p4 = {{mul_ln22_fu_705_p2[18:11]}};

assign tmp_5_fu_636_p4 = {{select_ln21_fu_561_p3[8:1]}};

assign tmp_6_fu_787_p4 = {{mul_ln41_fu_781_p2[16:10]}};

assign tmp_8_fu_882_p3 = {{px_1_fu_863_p9}, {1'd0}};

assign tmp_9_fu_964_p3 = {{px_3_reg_1475_pp0_iter15_reg}, {1'd0}};

assign tmp_fu_816_p7 = 'bx;

assign trunc_ln22_1_fu_728_p1 = grp_fu_602_p2[1:0];

assign trunc_ln22_fu_598_p1 = select_ln21_fu_561_p3[7:0];

assign trunc_ln36_1_fu_1145_p1 = gx_6_fu_1139_p3[9:0];

assign trunc_ln36_fu_1135_p1 = gy_5_fu_1129_p3[9:0];

assign trunc_ln49_fu_1197_p1 = abs3_fu_1189_p3[7:0];

assign zext_ln22_1_fu_721_p1 = tmp_2_fu_711_p4;

assign zext_ln22_fu_593_p1 = select_ln21_fu_561_p3;

assign zext_ln36_fu_950_p1 = conv_2218_pn_fu_943_p3;

assign zext_ln41_10_fu_1115_p1 = px_7_fu_1096_p9;

assign zext_ln41_1_fu_797_p1 = tmp_6_fu_787_p4;

assign zext_ln41_2_fu_855_p1 = px_fu_836_p9;

assign zext_ln41_3_fu_859_p1 = px_fu_836_p9;

assign zext_ln41_4_fu_807_p1 = tmp_7_reg_1355;

assign zext_ln41_6_fu_926_p1 = px_2_fu_910_p9;

assign zext_ln41_8_fu_1035_p1 = px_5_fu_1016_p9;

assign zext_ln41_9_fu_1039_p1 = px_5_fu_1016_p9;

assign zext_ln41_fu_774_p1 = add_ln41_reg_1349;

assign zext_ln42_1_fu_971_p1 = tmp_9_fu_964_p3;

assign zext_ln42_fu_999_p1 = shl_ln_fu_991_p3;

assign zext_ln43_1_fu_1086_p1 = add_ln43_fu_1080_p2;

assign zext_ln43_2_fu_890_p1 = tmp_8_fu_882_p3;

assign zext_ln43_fu_1076_p1 = shl_ln1_fu_1068_p3;

assign zext_ln49_fu_1201_p1 = abs3_fu_1189_p3;

always @ (posedge ap_clk) begin
    zext_ln22_reg_1275[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter1_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter2_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter3_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter4_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter5_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter6_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter7_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter8_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter9_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter10_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter11_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter12_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter13_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_reg_1275_pp0_iter14_reg[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    zext_ln22_1_reg_1325[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln22_1_reg_1325_pp0_iter13_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //sobel
