# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/Sobel_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sobel_design || ORIG_REF_NAME==Sobel_design} -quiet] -quiet

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_processing_system7_0_0/Sobel_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sobel_design_processing_system7_0_0 || ORIG_REF_NAME==Sobel_design_processing_system7_0_0} -quiet] -quiet

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sobel_design_axi_dma_0_0 || ORIG_REF_NAME==Sobel_design_axi_dma_0_0} -quiet] -quiet

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_sobel_0_0/Sobel_design_sobel_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sobel_design_sobel_0_0 || ORIG_REF_NAME==Sobel_design_sobel_0_0} -quiet] -quiet

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_proc_sys_reset_0_0/Sobel_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sobel_design_proc_sys_reset_0_0 || ORIG_REF_NAME==Sobel_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/Sobel_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Sobel_design_axi_smc_0 || ORIG_REF_NAME==Sobel_design_axi_smc_0} -quiet] -quiet

# XDC: C:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/Sobel_design_ooc.xdc
