# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/Sobel_design_axi_smc_0.xci
# IP: The module: 'Sobel_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/bd_b9ad.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_0/bd_b9ad_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_1/bd_b9ad_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_2/bd_b9ad_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_3/bd_b9ad_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_4/bd_b9ad_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_5/bd_b9ad_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_6/bd_b9ad_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_7/bd_b9ad_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_8/bd_b9ad_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_9/bd_b9ad_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_10/bd_b9ad_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_11/bd_b9ad_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_12/bd_b9ad_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_1/bd_b9ad_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_1/bd_b9ad_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_5/bd_b9ad_s00a2s_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_6/bd_b9ad_sarn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_7/bd_b9ad_srn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_8/bd_b9ad_sawn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_9/bd_b9ad_swn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_10/bd_b9ad_sbn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_11/bd_b9ad_m00s2a_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/Sobel_design_axi_smc_0.xci
# IP: The module: 'Sobel_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/bd_b9ad.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_0/bd_b9ad_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_1/bd_b9ad_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_2/bd_b9ad_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_3/bd_b9ad_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_4/bd_b9ad_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_5/bd_b9ad_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_6/bd_b9ad_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_7/bd_b9ad_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_8/bd_b9ad_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_9/bd_b9ad_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_10/bd_b9ad_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_11/bd_b9ad_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_12/bd_b9ad_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_1/bd_b9ad_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_1/bd_b9ad_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_5/bd_b9ad_s00a2s_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_6/bd_b9ad_sarn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_7/bd_b9ad_srn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_8/bd_b9ad_sawn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_9/bd_b9ad_swn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_10/bd_b9ad_sbn_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/bd_0/ip/ip_11/bd_b9ad_m00s2a_0_ooc.xdc

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
