# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0.xci
# IP: The module: 'Sobel_design_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0.xci
# IP: The module: 'Sobel_design_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/office/Desktop/X_MEN_SOBEL/Sobel_design/ip/Sobel_design_axi_dma_0_0/Sobel_design_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sobel_design_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
